language: android
dist: trusty
android:
  components:
    - build-tools-29.0.2
    - android-29
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-29
    - sys-img-armeabi-v7a-android-17